# Generated by Django 3.0.3 on 2020-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hospital', models.IntegerField()),
                ('today_confirmed', models.IntegerField()),
                ('total_confirmed', models.IntegerField()),
                ('today_recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('today_death', models.IntegerField()),
                ('total_death', models.IntegerField()),
            ],
        ),
    ]
