# Generated by Django 3.0.3 on 2020-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='Exempt_isolation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='Exempt_quarantine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='lockdown',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='present_isolation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='present_quarantine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='total_isolation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='total_quarantine',
            field=models.IntegerField(null=True),
        ),
    ]
