# Generated by Django 3.0.4 on 2020-04-03 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_myth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coronacounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_confirmed', models.IntegerField()),
                ('total_confirmed', models.IntegerField()),
                ('today_recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('today_death', models.IntegerField()),
                ('total_death', models.IntegerField()),
                ('total_quarantine', models.IntegerField(null=True)),
                ('released_quarantine', models.IntegerField(null=True)),
                ('present_quarantine', models.IntegerField(null=True)),
                ('total_isolation', models.IntegerField(null=True)),
                ('released_isolation', models.IntegerField(null=True)),
                ('present_isolation', models.IntegerField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
