# Generated by Django 3.0.4 on 2020-04-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_coronacounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('confirmed_cases', models.IntegerField()),
                ('up_case', models.IntegerField(null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division')),
            ],
        ),
    ]
