# Generated by Django 3.0.4 on 2020-04-16 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_area_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='up_case',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
