# Generated by Django 3.0.4 on 2020-04-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200416_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='date_posted',
            new_name='last_update',
        ),
    ]
