# Generated by Django 3.0.4 on 2020-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200416_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='present_isolation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='present_quarantine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='released_isolation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='released_quarantine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='total_isolation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coronacounter',
            name='total_quarantine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
