# Generated by Django 3.0.4 on 2020-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200416_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-confirmed_cases']},
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.CharField(default='Dhaka', max_length=220),
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.CharField(blank=True, max_length=220, unique=True),
        ),
    ]
