# Generated by Django 3.0.4 on 2020-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200416_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
