# Generated by Django 3.0.4 on 2020-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20200416_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='city',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
