# Generated by Django 3.0.4 on 2020-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200416_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['division', '-confirmed_cases']},
        ),
        migrations.AlterField(
            model_name='area',
            name='up_case',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
