# Generated by Django 3.0.4 on 2020-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200417_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='up_case',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
