# Generated by Django 3.0.4 on 2020-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200417_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['location', 'division', '-confirmed_cases']},
        ),
        migrations.AddField(
            model_name='coronacounter',
            name='today_tested',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='coronacounter',
            name='total_tested',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
